  
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

# pipeline:
#   - name: "nlp_spacy"                   # loads the spacy language model
#   - name: "tokenizer_spacy"             # splits the sentence into tokens
#   - name: "ner_crf"                     # uses the pretrained spacy NER model
#   - name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
#   - name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
#   - name: "ner_synonyms"                # trains the synonyms
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
